export const ADD_PERSONAL = 'ADD_PERSONAL'
export const ADD_WORK = 'ADD_WORK'
export const ADD_BUSINESS = 'ADD_BUSINESS'

export const REMOVE_PERSONAL = 'REMOVE_PERSONAL'
export const REMOVE_WORK = 'REMOVE_WORK'
export const REMOVE_BUSINESS = 'REMOVE_BUSINESS'

export const UPDATE_PERSONAL = 'UPDATE_PERSONAL'
export const UPDATE_WORK = 'UPDATE_WORK'
export const UPDATE_BUSINESS = 'UPDATE_BUSINESS'

export const PERSONAL_COUNT = 'PERSONAL_COUNT'
export const WORK_COUNT = 'WORK_COUNT'
export const BUSINESS_COUNT = 'BUSINESS_COUNT'